/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAO } from "./DAO";
export type { IERC20 } from "./IERC20";
export type { VarmaToken } from "./VarmaToken";
